services:
  misskaty:
    image: misskaty
    container_name: misskaty
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure

  # restarter:
  #   image: docker:cli
  #   volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
  #   command: ["/bin/sh", "-c", "while true; do sleep 259200; docker restart misskaty; done"]
  #   restart: on-failure
